/*
 * generated by Xtext
 */
package de.hsos.richwps.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.hsos.richwps.dSL.DSLPackage.eINSTANCE);
		return result;
	}
}
