/*
 * generated by Xtext
 */
package de.hsos.richwps.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DSLUiModule extends de.hsos.richwps.ui.AbstractDSLUiModule {
	public DSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
