/**
 * generated by Xtext
 */
package de.hsos.richwps.validation;

import de.hsos.richwps.validation.AbstractDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DSLValidator extends AbstractDSLValidator {
}
