/**
 * generated by Xtext
 */
package de.hsos.richwps.ui.contentassist;

import de.hsos.richwps.ui.contentassist.AbstractDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DSLProposalProvider extends AbstractDSLProposalProvider {
}
