/*
* generated by Xtext
*/
package de.hsos.richwps;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.hsos.richwps.ui.internal.DSLActivator.getInstance().getInjector("de.hsos.richwps.DSL");
	}
	
}
